CREATE TABLE todos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    text VARCHAR(4000) NOT NULL,
    completed TINYINT DEFAULT 0 NOT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

